kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: tutum/curl:trusty
    commands:
      - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/bin sh
      - arduino-cli core update-index
      - arduino-cli core install arduino:avr
      - arduino-cli compile --fqbn arduino:avr:mega ./Marlin/
