# automatically sets version information
# use the file as a githook.

VERSION_H="Marlin/src/inc/Version.h"
RAPIDIA_VERSION_H="Marlin/src/inc/RapidiaVersion.h"

if [ ! -f "$VERSION_H" ]
then
    echo "Failed to find $VERSION_H."
    exit 1
fi

# obtain version info from Marlin firmware
marlin_short_version=$(grep "#define SHORT_BUILD_VERSION" "$VERSION_H" | sed "s/.*VERSION \"\(.*\)\"/\1/")

# obtain previous version from Rapidia firmware
rapidia_version_previous="1.0.0"
if [ -f "$RAPIDIA_VERSION_H" ]
then
    rapidia_version_previous=$(grep "#define RAPIDIA_SHORT_BUILD_VERSION" "$RAPIDIA_VERSION_H" | sed "s/.*VERSION \"\(.*\)\"/\1/")
fi

rversion_major=$(echo "$rapidia_version_previous" | sed "s/\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/\1/")
rversion_minor=$(echo "$rapidia_version_previous" | sed "s/\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/\2/")
rversion_patch=$(echo "$rapidia_version_previous" | sed "s/\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/\3/")

echo "Previous version was $rversion_major.$rversion_minor.$rversion_patch"

# increment version
rversion_patch=$((rversion_patch+1))

# new version
rapidia_version="$rversion_major.$rversion_minor.$rversion_patch"

echo "New version is ${rapidia_version}"

# produce info file
echo "// This file was auto-generated by version-update.sh" > "$RAPIDIA_VERSION_H"
echo "// Do not edit by hand." >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"
echo "#pragma once" >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"
echo "#define MARLIN_SHORT_BUILD_VERSION \"$marlin_short_version\"" >> "$RAPIDIA_VERSION_H"
echo "#define RAPIDIA_SHORT_BUILD_VERSION \"$rapidia_version\"" >> "$RAPIDIA_VERSION_H"
echo "#define SHORT_BUILD_VERSION \"R\" RAPIDIA_SHORT_BUILD_VERSION \"/M\" MARLIN_SHORT_BUILD_VERSION" >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"
echo "#define DETAILED_BUILD_VERSION SHORT_BUILD_VERSION \"(Rapidia)\"" >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"
echo "#define STRING_DISTRIBUTION_DATE \"$(date)\"" >> "$RAPIDIA_VERSION_H"
