# automatically sets version information
# use the file as a githook.

VERSION_H="Marlin/Version.h"
RAPIDIA_VERSION_H="Marlin/RapidiaVersion.h"

#########################################################
# Command line parsing
update_minor=0
update_major=0

if [ $# != 1 ]
then
    echo "Usage: verion-update.sh [--minor] [--major]"
    echo "Either --minor or --major must be supplied."
    exit 2
fi

if [ $1 == "--minor" ]
then
    update_minor=1
fi

if [ $1 == "--major" ]
then
    update_major=1
fi

if [ ! -f "$VERSION_H" ]
then
    echo "Failed to find $VERSION_H."
    exit 1
fi

#########################################################
# Update firmware info.

# obtain version info from Marlin firmware
marlin_short_version=$(grep "#define SHORT_BUILD_VERSION" "$VERSION_H" | sed "s/.*VERSION \"\(.*\)\"/\1/")

# obtain previous version from Rapidia firmware
rapidia_version_previous="1.0"
if [ -f "$RAPIDIA_VERSION_H" ]
then
    rapidia_version_previous=$(grep "#define RAPIDIA_SHORT_BUILD_VERSION" "$RAPIDIA_VERSION_H" | sed "s/.*VERSION \"\(.*\)\"/\1/")
fi

rversion_major=$(echo "$rapidia_version_previous" | sed "s/\([0-9]\+\)\.\([0-9]\+\)/\1/")
rversion_minor=$(echo "$rapidia_version_previous" | sed "s/\([0-9]\+\)\.\([0-9]\+\)/\2/")

echo "Previous version was $rversion_major.$rversion_minor"

# increment version
if [ $update_major == 1 ]
then
    rversion_major=$((rversion_major+1))
    rversion_minor=0
fi

if [ $update_minor == 1 ]
then
    rversion_minor=$((rversion_minor+1))
fi

# new version
rapidia_version="$rversion_major.$rversion_minor"

echo "New version is ${rapidia_version}"

# produce info file
echo "// This file was auto-generated by version-update.sh" > "$RAPIDIA_VERSION_H"
echo "// Do not edit by hand." >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"
echo "#pragma once" >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"

# source revision default (git SHA)
echo "#ifndef RAPIDIA_SRC_REV" >> "$RAPIDIA_VERSION_H"
echo "  #define RAPIDIA_SRC_REV" >> "$RAPIDIA_VERSION_H"
echo "#endif" >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"

# version tag
echo "#define MARLIN_SHORT_BUILD_VERSION \"$marlin_short_version\"" >> "$RAPIDIA_VERSION_H"
echo "#define RAPIDIA_SHORT_BUILD_VERSION \"$rapidia_version\"" >> "$RAPIDIA_VERSION_H"
echo "#define SHORT_BUILD_VERSION MARLIN_SHORT_BUILD_VERSION \"r\" RAPIDIA_SHORT_BUILD_VERSION" >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"
echo "#define DETAILED_BUILD_VERSION SHORT_BUILD_VERSION \" (Rapidia)\"" >> "$RAPIDIA_VERSION_H"
echo "" >> "$RAPIDIA_VERSION_H"
echo "#define STRING_DISTRIBUTION_DATE \"$(date)\"" >> "$RAPIDIA_VERSION_H"
