// This file was auto-generated by version-update.sh
// Do not edit by hand.

#pragma once

#ifndef RAPIDIA_SRC_REV
  #define RAPIDIA_SRC_REV
#endif

#define MARLIN_SHORT_BUILD_VERSION "2.0.5.3"
#define RAPIDIA_SHORT_BUILD_VERSION "1.1.6"
#define SHORT_BUILD_VERSION "R" RAPIDIA_SHORT_BUILD_VERSION "/M" MARLIN_SHORT_BUILD_VERSION

#define DETAILED_BUILD_VERSION SHORT_BUILD_VERSION "(Rapidia)"

#define STRING_DISTRIBUTION_DATE "Wed, Jul  8, 2020  2:35:29 PM"
