// This file was auto-generated by version-update.sh
// Do not edit by hand.

#pragma once

#define MARLIN_SHORT_BUILD_VERSION "2.0.5"
#define RAPIDIA_SHORT_BUILD_VERSION "1.0.5"
#define SHORT_BUILD_VERSION "R" RAPIDIA_SHORT_BUILD_VERSION "/M" MARLIN_SHORT_BUILD_VERSION

#define DETAILED_BUILD_VERSION SHORT_BUILD_VERSION "(Rapidia)"

#define STRING_DISTRIBUTION_DATE "Wed Apr 15 12:37:48 PDT 2020"
