#pragma once

#if ENABLED(RAPIDIA_PAUSE) && !ENABLED(RAPIDIA_BLOCK_SOURCE)
  #error "RAPIDIA_PAUSE requires RAPIDIA_BLOCK_SOURCE"
#endif

#if ENABLED(RAPIDIA_LINE_AUTO_REPORTING) &&! ENABLED(RAPIDIA_BLOCK_SOURCE)
  #error "RAPIDIA_LINE_AUTO_REPORTING requires RAPIDIA_BLOCK_SOURCE"
#endif

#if !ENABLED(EMERGENCY_PARSER)
  #if ENABLED(RAPIDIA_EMERGENCY_STOP_INTERRUPT) || ENABLED(RAPIDIA_EOT_EMERGENCY_STOP) || ENABLED(RAPIDIA_KILL_RECOVERY)
    #error "Rapidia emergency stop features require emergency parser."
  #endif
#endif

#if ENABLED(RAPIDIA_KILL_RECOVERY)
  #ifndef __AVR_ATmega2560__
    #error RAPIDIA_KILL_RECOVERY is coded specifically for ATmega2560
  #endif
#endif

#if ENABLED(RAPIDIA_MILEAGE)
  #ifndef RAPIDIA_MILEAGE_EEPROM_START
    #error RAPIDIA_MILEAGE defined but not RAPIDIA_MILEAGE_EEPROM_START
  #endif
#endif

#if ENABLED(RAPIDIA_STACK_USAGE) && !ENABLED(RAPIDIA_STACK_UTIL)
    #error RAPIDIA_STACK_USAGE requires RAPIDIA_STACK_UTIL
#endif