// This file was auto-generated by version-update.sh
// Do not edit by hand.

#pragma once

#ifndef RAPIDIA_SRC_REV
  #define RAPIDIA_SRC_REV
#endif

#define MARLIN_SHORT_BUILD_VERSION "2.0.5"
#define RAPIDIA_SHORT_BUILD_VERSION "1.1.1"
#define SHORT_BUILD_VERSION "R" RAPIDIA_SHORT_BUILD_VERSION "/M" MARLIN_SHORT_BUILD_VERSION

#define DETAILED_BUILD_VERSION SHORT_BUILD_VERSION "(Rapidia)"
#define STRING_DISTRIBUTION_DATE "Fri May 29 16:43:13 PDT 2020"
