// This file was auto-generated by version-update.sh
// Do not edit by hand.

#pragma once

#ifndef RAPIDIA_SRC_REV
  #define RAPIDIA_SRC_REV
#endif

#define MARLIN_SHORT_BUILD_VERSION "1.1.9"
#define RAPIDIA_SHORT_BUILD_VERSION "1.0"
#define SHORT_BUILD_VERSION MARLIN_SHORT_BUILD_VERSION "r" RAPIDIA_SHORT_BUILD_VERSION

#define DETAILED_BUILD_VERSION SHORT_BUILD_VERSION " (Rapidia)"

#define STRING_DISTRIBUTION_DATE "Thu Jul 16 11:37:45 PDT 2020"
